"""
Environment configuration constants.
"""

GEMINI_API_KEY_NAME = "GEMINI_KEY"
OPENAI_API_KEY_NAME = "OPEN_AI_KEY"

KEY_LOCATION_NAME = "KEY_LOCATION"
KEY_LOCATION_LOCAL = "LOCAL"
KEY_LOCATION_AWS_SM = "AWS_SM"
VALID_KEY_LOCATIONS = (KEY_LOCATION_LOCAL, KEY_LOCATION_AWS_SM)

SECRET_NAME_KEY = "SECRET_NAME"

GEMINI_KEY_TYPE_NAME = "GEMINI_KEY_TYPE"
GEMINI_KEY_TYPE_API_KEY = "GEMINI_KEY"
GEMINI_KEY_TYPE_SERVICE_ACC_JSON = "SERVICE_ACC_JSON"
VALID_GEMINI_KEY_TYPES = (GEMINI_KEY_TYPE_API_KEY, GEMINI_KEY_TYPE_SERVICE_ACC_JSON)

GEMINI_SERVICE_ACCOUNT_FILE_NAME = "GEMINI_SERVICE_ACCOUNT_FILE"
GEMINI_SERVICE_ACCOUNT_JSON_NAME = "GEMINI_SERVICE_ACCOUNT_JSON"
GEMINI_PROJECT_NAME = "GEMINI_PROJECT"
GEMINI_LOCATION_NAME = "GEMINI_LOCATION"

GEMINI_SERVICE_ACCOUNT_SCOPES = (
    "https://www.googleapis.com/auth/cloud-platform",
)
DEFAULT_GEMINI_LOCATION = "us-central1"

ROUTED_SECRET_NAMES = frozenset({
    "DATABASE_URL",
    "SQLITE_URL",
    "SQLITE_DB_PATH",
    "POSTGRES_URL",
    "MYSQL_URL",
    GEMINI_API_KEY_NAME,
    GEMINI_SERVICE_ACCOUNT_JSON_NAME,
    OPENAI_API_KEY_NAME,
    "ANTHROPIC_KEY",
    "PERPLEXITY_KEY",
    "OLLAMA_URL",
    "OLLAMA_KEY",
    "VLLM_URL",
    "VLLM_KEY",
    "AWS_ACCESS_KEY_ID",
    "AWS_SECRET_ACCESS_KEY",
    "AWS_SESSION_TOKEN",
    "AWS_S3_BUCKET",
})

